golchivoapp/apps/jornada_actual/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth.decorators import login_required
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'jornadaApi', views.JornadaViewSet)
router.register(r'alineacionApi', views.AlineacionViewSet)
router.register(r'directoApi', views.DirectoViewSet)
router.register(r'cronicaApi', views.CronicaViewSet)
router.register(r'resultadoApi', views.ResultadoViewSet)
router.register(r'alineacionesApi', views.AlineacionesViewSet)

urlpatterns = [
    # Jornadas
    url(r'^$', login_required(views.jornada_list), name="list"),
    url(r'^create/$', login_required(views.jornada_create), name="jornada_create"),
    #url(r'^(?P<id>\d+)/$',login_required(views.jornada_detail), name='jornada_detail'),
    url(r'^(?P<id>\d+)/edit/$',login_required(views.jornada_update), name='jornada_update'),
    #api
    url(r'^', include(router.urls)),

    #Alineaciones
    url(r'^alineacion/$', login_required(views.alineacion_list), name="alin_list_act"),
    url(r'^alineacion/create/$', login_required(views.alinecion_create), name="alin_create"),
    url(r'^alineacion/(?P<id>\d+)/edit/$',login_required(views.alineacion_update), name='alin_update'),
    url(r'^alineacion/(?P<id>\d+)/delete/$',login_required(views.alineacion_delete), name='alin_delete'),
 #    #api
 #    url(r'^alienacion/', include(router.urls)),

 #    #Directo

	# #api
 #    url(r'^directo/', include(router.urls)),    

 #    #Cronica
    url(r'^cronica/$', login_required(views.cronica_list), name="cronica_list"),
    url(r'^cronica/(?P<id>\d+)/edit/$',login_required(views.cronica_update), name='cronica_update'),
	# #api
 #    url(r'^cronica/', include(router.urls)),

     #    #Resultados
    url(r'^resultados/$', login_required(views.resultado_list), name="result_list"),
    url(r'^resultados/(?P<id>\d+)/edit/$',login_required(views.resultado_update), name='result_update'),
    #url(r'^resultados/(?P<id>\d+)/delete/$',login_required(views.resultado_delete), name='result_delete'),
 #    #api
 #    url(r'^resultados/', include(router.urls)),

]

golchivoapp/golchivoapp/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required
from apps.jornada_anterior import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login_required(views.home), name='home'),
    url(r'^jornada_anterior/', include('apps.jornada_anterior.urls', namespace="jornada_anterior")),
    url(r'^jornada_actual/', include('apps.jornada_actual.urls', namespace="jornada_actual")),
    url(r'^jornada_siguiente/', include('apps.jornada_siguiente.urls', namespace="jornada_siguiente")),
    url(r'^tablas/', include('apps.tablas.urls', namespace="tablas")),
    url(r'^equipo/', include('apps.equipo.urls', namespace="equipo")),
    url(r'^posts/', include('apps.posts.urls', namespace='posts')),

    url(r'^accounts/login/', login, {'template_name':'index.html'}, name="login"),
    #url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

golchivoapp/templates/jornadas/jornada_create.html
{% extends 'base/base.html' %}

{% load crispy_forms_tags%}


{% block content %}
    <div class="col-sm-6 col-sm-offset-3">

        <h1>{{template_title}}</h1>

        <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
            {{form|crispy}}
            {{ formjact|crispy }}
            {{ fromjsig|crispy }}
            <button class="btn btn-primary" type="submit">{{btn_name}}</button>
        </form>
    </div>
{% endblock %}

golchivoapp/templates/jornadas/jornada_detail.html
<h1>{{template_title}}</h1>

{{instance.titulo}} </br>

{{instance.fecha}} </br>
{{instance.horario}} </br>
{{instance.estadio}} </br>
{{instance.nom_local}} </br>
{{instance.nom_visita}} </br>
{{instance.marcador}} </br>
{{instance.estado}} </br>

golchivoapp/templates/jornadas/jornada_list.html
{% extends "base/base.html" %}
{% block head_title %} Jornadas | {{block.super}} {% endblock head_title %}


{% block content %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-4 text-center">
			{% if object_list %}
			{% for item in object_list %}
						<h2>{{item.titulo}}</h2>
				<div class="panel panel-default text-left">
					<div class="panel-body">							
						<FONT SIZE=4>Fecha:</font> {{item.fecha}}<br>
						<FONT SIZE=4>Horario:</font> {{item.horario}}<br>
						<FONT SIZE=4>Estadio:</font> {{item.estadio}}<br>
						<FONT SIZE=4>Local:</font> {{item.nom_local}}<br>
						<FONT SIZE=4>Visita:</font> {{item.nom_visita}}<br>
						<FONT SIZE=4>Marcador:</font> {{item.marcador}}<br>
						<FONT SIZE=4>Estado:</font> {{item.estado}}<br>
						<hr/>
						<a class="btn btn-primary" href="{% url 'jornada_anterior:jornada_update' item.id %}">Editar</a>
					</div>
				</div>
			{% endfor%}	
			{% endif%}
			</div>
		<!-- 	<div class=" col-sm-12 col-md-2">
			
			</div> -->
			<div class="col-md-8 text-center">
				<h2>Alineacion</h2>
				<div class="panel panel-default text-left">
					<div class="panel-body">
					
						<table class="table text-left">
						<thead>
							<tr>
								<td>Nombre Jugador Local</td>
								<td>No.</td>
								<td>Nombre jugador visita</td>
								<td>No.</td>
							</tr>
						</thead>
							{% if object_list %}
							{% for item in object_list %}
							<tbody>   
							<tr>
								<td>{{item.alineacion.nombre_jugador_local}}</td>
								<td>{{item.alineacion.numero_jugador_local}}</td>
								<td>{{item.alineacion.nombre_jugador_visita}}</td>
								<td>{{item.alineacion.numero_jugador_visita}}</td>
							</tr>
							</tbody>
							{% endfor%}
							{% endif %}
						</table>	

						{{item.alineacion.nombre_jugador_local}}
						
					</div>
				</div>
			</div>
		</div>
	</div>


{% endblock %}

<!-- <table class="table text-left">
							<tbody>
								<tr>
									<td><h4><strong>Fecha</strong></h4></td>
									<td>{{item.fecha}}</td>
								</tr>
								<tr>
									<td>Horario</td>
									<td>{{item.horario}}</td>
								</tr>
								<tr>
									<td>Estadio</td>
									<td>{{item.estadio}}</td>
								</tr>
								<tr>
									<td>Equipo local</td>
									<td>{{item.nom_local}}</td>
								</tr>
								<tr>
									<td>Equipo visita</td>
									<td>{{item.nom_visita}}</td>
								</tr>
								<tr>
									<td>Marcador</td>
									<td>{{item.marcador}}</td>
								</tr>
								<tr>
									<td>Estado</td>
									<td>{{item.estado}}</td>
								</tr>
								<a class="btn btn-primary" href="#">Editar</a>
							</tbody>
						</table> -->


						<table class="table text-left">
						<thead>
							<tr>
								<td>id</td>
								<td>Nombre Jugador Local</td>
								<td>No.</td>
								<td>Nombre jugador visita</td>
								<td>No.</td>
							</tr>
						</thead>
							{% for alin in object_list_alin %} 
							<tbody>   
							<tr>

								<td>{{alin.id}}</td>
								{% if alin.nombre_jugador_local %}
								<td>{{alin.nombre_jugador_local}}</td>
								{% endif %}
								<td>{{alin.numero_jugador_local}}</td>
								<td>{{alin.nombre_jugador_visita}}</td>
								<td>{{alin.numero_jugador_visita}}</td>
							</tr>
							</tbody>
							{% endfor%}
						</table>	

golchivoapp/templates/jornadas/jornada_list_actual.html
{% extends "base/base.html" %}
{% block head_title %} Jornadas | {{block.super}} {% endblock head_title %}


{% block content %}
	<div class="container-fluid">
		<div class="row">
        <div class="col-md-2">

        </div>
			<div class="col-md-4 text-center">
			{% if object_list %}
			{% for item in object_list %}
                <h2>{{item.titulo}}</h2>
				<div class="panel panel-default text-left">
					<div class="panel-body">							
						<FONT SIZE=4>Fecha:</font> {{item.fecha}}<br>
						<FONT SIZE=4>Horario:</font> {{item.horario}}<br>
						<FONT SIZE=4>Estadio:</font> {{item.estadio}}<br>
						<FONT SIZE=4>Local:</font> {{item.nom_local}}<br>
						<FONT SIZE=4>Visita:</font> {{item.nom_visita}}<br>
						<FONT SIZE=4>Marcador:</font> {{item.marcador}}<br>
						<FONT SIZE=4>Estado:</font> {{item.estado}}<br>
                        <FONT SIZE=4>Tab:</font> {{item.num_tab}}<br>
						<hr/>


						<a class="btn btn-primary" href="{% url 'jornada_actual:jornada_update' item.id %}">Editar</a>
					</div>
				</div>
			{% endfor%}	
			{% endif%}
			</div>
		<!-- 	<div class=" col-sm-12 col-md-2">
			
			</div> -->
			<div class="col-md-2 ">
                <h1>accesos</h1>
				<div class="panel panel-default text-center">

					<div class="panel-body">
                        <a class="btn btn-primary" href="{% url 'jornada_actual:alin_list_act' %}">Alineaciones</a> </br> </br>
                        <a class="btn btn-primary" href="http://127.0.0.1:8000/jornada_actual/directoApi/">Directo</a></br></br>
                        <a class="btn btn-primary" href="{% url 'jornada_actual:cronica_list' %}">Cronica</a></br></br>
                        <a class="btn btn-primary" href="{% url 'jornada_actual:result_list' %}">Resultados</a></br></br>

					</div>
				</div>
			</div>
		</div>
	</div>


{% endblock %}

<!-- <table class="table text-left">
							<tbody>
								<tr>
									<td><h4><strong>Fecha</strong></h4></td>
									<td>{{item.fecha}}</td>
								</tr>
								<tr>
									<td>Horario</td>
									<td>{{item.horario}}</td>
								</tr>
								<tr>
									<td>Estadio</td>
									<td>{{item.estadio}}</td>
								</tr>
								<tr>
									<td>Equipo local</td>
									<td>{{item.nom_local}}</td>
								</tr>
								<tr>
									<td>Equipo visita</td>
									<td>{{item.nom_visita}}</td>
								</tr>
								<tr>
									<td>Marcador</td>
									<td>{{item.marcador}}</td>
								</tr>
								<tr>
									<td>Estado</td>
									<td>{{item.estado}}</td>
								</tr>
								<a class="btn btn-primary" href="#">Editar</a>
							</tbody>
						</table> -->


						<table class="table text-left">
						<thead>
							<tr>
								<td>id</td>
								<td>Nombre Jugador Local</td>
								<td>No.</td>
								<td>Nombre jugador visita</td>
								<td>No.</td>
							</tr>
						</thead>
							{% for alin in object_list_alin %} 
							<tbody>   
							<tr>

								<td>{{alin.id}}</td>
								{% if alin.nombre_jugador_local %}
								<td>{{alin.nombre_jugador_local}}</td>
								{% endif %}
								<td>{{alin.numero_jugador_local}}</td>
								<td>{{alin.nombre_jugador_visita}}</td>
								<td>{{alin.numero_jugador_visita}}</td>
							</tr>
							</tbody>
							{% endfor%}
						</table>	

golchivoapp/templates/jornadas/jornada_list_siguiente.html
{% extends "base/base.html" %}
{% block head_title %} Jornadas | {{block.super}} {% endblock head_title %}


{% block content %}
	<div class="container-fluid">
		<div class="row">
        <div class="col-md-4">

        </div>
			<div class="col-md-4 text-center">
			{% if object_list %}
			{% for item in object_list %}
                <h2>{{item.titulo}}</h2>
				<div class="panel panel-default text-left">
					<div class="panel-body">							
						<FONT SIZE=4>Fecha:</font> {{item.fecha}}<br>
						<FONT SIZE=4>Horario:</font> {{item.horario}}<br>
						<FONT SIZE=4>Estadio:</font> {{item.estadio}}<br>
						<FONT SIZE=4>Local:</font> {{item.nom_local}}<br>
						<FONT SIZE=4>Visita:</font> {{item.nom_visita}}<br>
						<FONT SIZE=4>Marcador:</font> {{item.marcador}}<br>
						<FONT SIZE=4>Estado:</font> {{item.estado}}<br>
						<hr/>


						<a class="btn btn-primary" href="{% url 'jornada_siguiente:jornada_update' item.id %}">Editar</a>
					</div>
				</div>
			{% endfor%}	
			{% endif%}
			</div>
			<div class="col-md-2 ">

			</div>
		</div>
	</div>
{% endblock %}