golchivoapp/apps/posts/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='list'),
    url(r'^create/$', login_required(views.post_create), name='create'),
    # url(r'^(?P<id>\d+)/$', views.post_detail, name='detail'),
    # url(r'^(?P<id>\d+)/edit/$', views.post_update, name='update'),
    # url(r'^(?P<id>\d+)/delete/$', views.post_delete, name='delete'),

    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', login_required(views.post_update), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', login_required(views.post_delete), name='delete'),
]

golchivoapp/apps/tablas/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'posicionesApi',views.PosicionViewset)
router.register(r'goleadoresApi',views.GoleadorViewset)
router.register(r'tarjetaApi',views.TarjetaViewset)

urlpatterns = [
	#api posiciones
	url(r'^posiciones/', include(router. urls)),

    url(r'^$', login_required(views.Position_list), name="list"),
    url(r'^posicion/(?P<id>\d+)/edit/$',login_required(views.Position_update), name='pos_update'),

	
	#api goleadores
	url(r'^goleadores/', include(router. urls)),
    url(r'^goleador/$', login_required(views.Goldeador_list), name="gol_list"),
    url(r'^goleador/create/$', login_required(views.goleador_create), name="gol_create"),
    url(r'^goleador/(?P<id>\d+)/edit/$',login_required(views.goleador_update), name='gol_update'),

	#api tarjetas
	url(r'^tarjetas/', include(router. urls)),
    url(r'^tarjeta/$', login_required(views.tarjetas_list), name="tarj_list"),
    url(r'^tarjeta/create/$', login_required(views.tarjeta_create), name="tarj_create"),
    url(r'^tarjeta/(?P<id>\d+)/edit/$',login_required(views.tajeta_update), name='tarj_update'),

]

golchivoapp/golchivoapp/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required
from apps.jornada_anterior import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login_required(views.home), name='home'),
    url(r'^jornada_anterior/', include('apps.jornada_anterior.urls', namespace="jornada_anterior")),
    url(r'^jornada_actual/', include('apps.jornada_actual.urls', namespace="jornada_actual")),
    url(r'^jornada_siguiente/', include('apps.jornada_siguiente.urls', namespace="jornada_siguiente")),
    url(r'^tablas/', include('apps.tablas.urls', namespace="tablas")),
    url(r'^equipo/', include('apps.equipo.urls', namespace="equipo")),
    url(r'^posts/', include('apps.posts.urls', namespace='posts')),

    url(r'^accounts/login/', login, {'template_name':'index.html'}, name="login"),
    #url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

golchivoapp/templates/base/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title> {% block head_title %}Gol Chivo{% endblock head_title %} </title>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	
</head>
<body>

<!-- Navbar -->
{% if user.is_authenticated %}
  {% include "base/navbar.html" %}
{% endif %}
<!-- fin Navbar -->


{% block content %}
	
{% endblock content %}


<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>

</body>
</html>

golchivoapp/templates/base/home.html
{% extends "base/base.html" %}
{% block head_title %} home | {{block.super}} {% endblock head_title %}


{% block content %}
	<div class="container-fluid">
    
		<div class="row">
		
			<div class="col-md-4 text-center">
				<a href="{% url 'jornada_anterior:list' %}" class="list-group-item"><h4>Jornada anterior</h4></a>
			</div>
			<div class=" col-md-4 text-center">
				<a href="{% url 'jornada_actual:list' %}" class="list-group-item"><h4>Jornada actual</h4></a>
			</div>
			<div class="col-md-4 text-center">
				<a href="{% url 'jornada_siguiente:list' %}" class="list-group-item"><h4>Jornada siguiente</h4></a>
			</div>
			
		</div>
	</div>
{% endblock content %}

golchivoapp/templates/base/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><strong>Gol Chivo app</strong></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="{% url 'home' %}">Jornadas<span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'posts:list' %}">Blog</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Tablas<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'tablas:list' %}">Posiciones</a></li>
            <li><a href="{% url 'tablas:gol_list' %}">Goleadores</a></li>
            <li><a href="{% url 'tablas:tarj_list' %}">Amarillas</a></li>
            <li class="divider"></li>
            <li><a href="#">plantel</a></li>
          </ul>
        </li>
        <li><a href="{% url 'logout' %}">Cerrar sesion</a></li>
      </ul>
    </div>
  </div>
</nav>