golchivoapp/apps/jornada_actual/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth.decorators import login_required
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'jornadaApi', views.JornadaViewSet)
router.register(r'alineacionApi', views.AlineacionViewSet)
router.register(r'directoApi', views.DirectoViewSet)
router.register(r'cronicaApi', views.CronicaViewSet)
router.register(r'resultadoApi', views.ResultadoViewSet)
router.register(r'alineacionesApi', views.AlineacionesViewSet)

urlpatterns = [
    # Jornadas
    url(r'^$', login_required(views.jornada_list), name="list"),
    url(r'^create/$', login_required(views.jornada_create), name="jornada_create"),
    #url(r'^(?P<id>\d+)/$',login_required(views.jornada_detail), name='jornada_detail'),
    url(r'^(?P<id>\d+)/edit/$',login_required(views.jornada_update), name='jornada_update'),
    #api
    url(r'^', include(router.urls)),

    #Alineaciones
    url(r'^alineacion/$', login_required(views.alineacion_list), name="alin_list_act"),
    url(r'^alineacion/create/$', login_required(views.alinecion_create), name="alin_create"),
    url(r'^alineacion/(?P<id>\d+)/edit/$',login_required(views.alineacion_update), name='alin_update'),
    url(r'^alineacion/(?P<id>\d+)/delete/$',login_required(views.alineacion_delete), name='alin_delete'),
 #    #api
 #    url(r'^alienacion/', include(router.urls)),

 #    #Directo

	# #api
 #    url(r'^directo/', include(router.urls)),    

 #    #Cronica
    url(r'^cronica/$', login_required(views.cronica_list), name="cronica_list"),
    url(r'^cronica/(?P<id>\d+)/edit/$',login_required(views.cronica_update), name='cronica_update'),
	# #api
 #    url(r'^cronica/', include(router.urls)),

     #    #Resultados
    url(r'^resultados/$', login_required(views.resultado_list), name="result_list"),
    url(r'^resultados/(?P<id>\d+)/edit/$',login_required(views.resultado_update), name='result_update'),
    #url(r'^resultados/(?P<id>\d+)/delete/$',login_required(views.resultado_delete), name='result_delete'),
 #    #api
 #    url(r'^resultados/', include(router.urls)),

]

golchivoapp/apps/posts/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='list'),
    url(r'^create/$', login_required(views.post_create), name='create'),
    # url(r'^(?P<id>\d+)/$', views.post_detail, name='detail'),
    # url(r'^(?P<id>\d+)/edit/$', views.post_update, name='update'),
    # url(r'^(?P<id>\d+)/delete/$', views.post_delete, name='delete'),

    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', login_required(views.post_update), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', login_required(views.post_delete), name='delete'),
]

golchivoapp/golchivoapp/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required
from apps.jornada_anterior import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login_required(views.home), name='home'),
    url(r'^jornada_anterior/', include('apps.jornada_anterior.urls', namespace="jornada_anterior")),
    url(r'^jornada_actual/', include('apps.jornada_actual.urls', namespace="jornada_actual")),
    url(r'^jornada_siguiente/', include('apps.jornada_siguiente.urls', namespace="jornada_siguiente")),
    url(r'^tablas/', include('apps.tablas.urls', namespace="tablas")),
    url(r'^equipo/', include('apps.equipo.urls', namespace="equipo")),
    url(r'^posts/', include('apps.posts.urls', namespace='posts')),

    url(r'^accounts/login/', login, {'template_name':'index.html'}, name="login"),
    #url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

golchivoapp/templates/cronicas/cronica_create.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags%}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">

        <form method="post" action="" >
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-primary" type="submit">{{btn_name}}</button>
            <a class="btn btn-primary" href="{% url 'jornada_actual:cronica_list' %}">Cancelar</a>
        </form>
    </div>
{% endblock %}

golchivoapp/templates/cronicas/cronica_detail.html
<h1>{{template_title}}</h1>

{{instance.titulo}} </br>
{{instance.cronica}}</br>

golchivoapp/templates/cronicas/cronica_list.html
{% extends 'base/base.html' %}

{% block content %}

    <div class="col-md-2">

    </div>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6">
                <h1>{{template_title}} </h1>
                {% for item in object_list %}
                <h3>Titulo:</h3>
                <p>{{item.titulo}}</p>
                <h3>Cronica:</h3>
                <p>{{item.cronica|linebreaks}}</p>
                <P>
                <a class="btn btn-primary" href="{% url 'jornada_anterior:cronica_update' item.id %}">Editar</a></br></br>
                </P>
                {% endfor%}
			</div>
            <div class="col-md-2 ">
                <h1>accesos</h1>
                <div class="panel panel-default text-center">
                    <div class="panel-body">
                        <a class="btn btn-primary" href="{% url 'jornada_anterior:list' %}">Jornada</a></br></br>
                        <a class="btn btn-primary" href="{% url 'jornada_anterior:result_list' %}">Resultados</a></br></br>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}



    <h1>{{template_title}} </h1>

    {% for item in object_list %}
        <h4>{{item.titulo}}</h4>
        <h4>{{item.cronica}}</h4>

    {% endfor%}

golchivoapp/templates/cronicas/cronica_list_actual.html
{% extends "base/base.html" %}
{% block head_title %} Jornadas | {{block.super}} {% endblock head_title %}


{% block content %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-8">
                <h1>{{template_title}} </h1>
                {% for item in object_list %}
                <h3>Titulo:</h3>
                <p>{{item.titulo}}</p>
                <h3>Cronica:</h3>
                <p>{{item.cronica|linebreaks}}</p>
                <P>
                <a class="btn btn-primary" href="{% url 'jornada_actual:cronica_update' item.id %}">Editar</a></br></br>
                </P>
                {% endfor%}
			</div>
			<div class="col-md-2 ">
                <h1>accesos</h1>
				<div class="panel panel-default text-center">

					<div class="panel-body">
                        <a class="btn btn-primary" href="{% url 'jornada_actual:list' %}">Jornada</a></br></br>
                        <a class="btn btn-primary" href="{% url 'jornada_actual:alin_list_act' %}">Alineaciones</a> </br> </br>
                        <a class="btn btn-primary" href="http://127.0.0.1:8000/jornada_actual/directoApi/">Directo</a></br></br>
                        <a class="btn btn-primary" href="{% url 'jornada_actual:result_list' %}">Resultados</a></br></br>
					</div>
				</div>
			</div>
		</div>
	</div>


{% endblock %}