golchivoapp/apps/jornada_actual/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth.decorators import login_required
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'jornadaApi', views.JornadaViewSet)
router.register(r'alineacionApi', views.AlineacionViewSet)
router.register(r'directoApi', views.DirectoViewSet)
router.register(r'cronicaApi', views.CronicaViewSet)
router.register(r'resultadoApi', views.ResultadoViewSet)
router.register(r'alineacionesApi', views.AlineacionesViewSet)

urlpatterns = [
    # Jornadas
    url(r'^$', login_required(views.jornada_list), name="list"),
    url(r'^create/$', login_required(views.jornada_create), name="jornada_create"),
    #url(r'^(?P<id>\d+)/$',login_required(views.jornada_detail), name='jornada_detail'),
    url(r'^(?P<id>\d+)/edit/$',login_required(views.jornada_update), name='jornada_update'),
    #api
    url(r'^', include(router.urls)),

    #Alineaciones
    url(r'^alineacion/$', login_required(views.alineacion_list), name="alin_list_act"),
    url(r'^alineacion/create/$', login_required(views.alinecion_create), name="alin_create"),
    url(r'^alineacion/(?P<id>\d+)/edit/$',login_required(views.alineacion_update), name='alin_update'),
    url(r'^alineacion/(?P<id>\d+)/delete/$',login_required(views.alineacion_delete), name='alin_delete'),
 #    #api
 #    url(r'^alienacion/', include(router.urls)),

 #    #Directo

	# #api
 #    url(r'^directo/', include(router.urls)),    

 #    #Cronica
    url(r'^cronica/$', login_required(views.cronica_list), name="cronica_list"),
    url(r'^cronica/(?P<id>\d+)/edit/$',login_required(views.cronica_update), name='cronica_update'),
	# #api
 #    url(r'^cronica/', include(router.urls)),

     #    #Resultados
    url(r'^resultados/$', login_required(views.resultado_list), name="result_list"),
    url(r'^resultados/(?P<id>\d+)/edit/$',login_required(views.resultado_update), name='result_update'),
    #url(r'^resultados/(?P<id>\d+)/delete/$',login_required(views.resultado_delete), name='result_delete'),
 #    #api
 #    url(r'^resultados/', include(router.urls)),

]

golchivoapp/apps/posts/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='list'),
    url(r'^create/$', login_required(views.post_create), name='create'),
    # url(r'^(?P<id>\d+)/$', views.post_detail, name='detail'),
    # url(r'^(?P<id>\d+)/edit/$', views.post_update, name='update'),
    # url(r'^(?P<id>\d+)/delete/$', views.post_delete, name='delete'),

    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', login_required(views.post_update), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', login_required(views.post_delete), name='delete'),
]

golchivoapp/golchivoapp/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required
from apps.jornada_anterior import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login_required(views.home), name='home'),
    url(r'^jornada_anterior/', include('apps.jornada_anterior.urls', namespace="jornada_anterior")),
    url(r'^jornada_actual/', include('apps.jornada_actual.urls', namespace="jornada_actual")),
    url(r'^jornada_siguiente/', include('apps.jornada_siguiente.urls', namespace="jornada_siguiente")),
    url(r'^tablas/', include('apps.tablas.urls', namespace="tablas")),
    url(r'^equipo/', include('apps.equipo.urls', namespace="equipo")),
    url(r'^posts/', include('apps.posts.urls', namespace='posts')),

    url(r'^accounts/login/', login, {'template_name':'index.html'}, name="login"),
    #url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

golchivoapp/templates/alineaciones/alineacion_create.html
{% include 'base/base.html' %}
{% load crispy_forms_tags %}

<div class="col-sm-6 col-sm-offset-3">
    <h1>{{template_title}}</h1>
    <form method="post" action="">
    {% csrf_token %}
        <table class="table">
        <tr>
          <td>Jugador local</td>
          <td>No.</td>
          <td>Jugador vista</td>
          <td>No.</td>
        </tr>
        <tr>
          <td>{{form.nombreJL1}}</td>
          <td>{{form.numeroJL1}}</td>
          <td>{{form.nombreJV1}}</td>
          <td>{{form.numeroJV1}}</td>
        </tr>
            <tr>
          <td>{{form.nombreJL2}}</td>
          <td>{{form.numeroJL2}}</td>
          <td>{{form.nombreJV2}}</td>
          <td>{{form.numeroJV2}}</td>
        </tr>
            <tr>
          <td>{{form.nombreJL3}}</td>
          <td>{{form.numeroJL3}}</td>
          <td>{{form.nombreJV3}}</td>
          <td>{{form.numeroJV3}}</td>
        </tr>
            <tr>
          <td>{{form.nombreJL4}}</td>
          <td>{{form.numeroJL4}}</td>
          <td>{{form.nombreJV4}}</td>
          <td>{{form.numeroJV4}}</td>
        </tr>
            <tr>
          <td>{{form.nombreJL5}}</td>
          <td>{{form.numeroJL5}}</td>
          <td>{{form.nombreJV5}}</td>
          <td>{{form.numeroJV5}}</td>
        </tr>
            <tr>
          <td>{{form.nombreJL6}}</td>
          <td>{{form.numeroJL6}}</td>
          <td>{{form.nombreJV6}}</td>
          <td>{{form.numeroJV6}}</td>
        </tr>
            <tr>
          <td>{{form.nombreJL7}}</td>
          <td>{{form.numeroJL7}}</td>
          <td>{{form.nombreJV7}}</td>
          <td>{{form.numeroJV7}}</td>
        </tr>
            <tr>
          <td>{{form.nombreJL8}}</td>
          <td>{{form.numeroJL8}}</td>
          <td>{{form.nombreJV8}}</td>
          <td>{{form.numeroJV8}}</td>
        </tr>
            <tr>
          <td>{{form.nombreJL9}}</td>
          <td>{{form.numeroJL9}}</td>
          <td>{{form.nombreJV9}}</td>
          <td>{{form.numeroJV9}}</td>
        </tr>
            <tr>
          <td>{{form.nombreJL10}}</td>
          <td>{{form.numeroJL10}}</td>
          <td>{{form.nombreJV10}}</td>
          <td>{{form.numeroJV10}}</td>
        </tr>
            <tr>
          <td>{{form.nombreJL11}}</td>
          <td>{{form.numeroJL11}}</td>
          <td>{{form.nombreJV11}}</td>
          <td>{{form.numeroJV11}}</td>
        </tr>
            <tr>
          <td>{{form.nombreDtL}}</td>
          <td>{{form.numeroDtL}}</td>
          <td>{{form.nombreDtV}}</td>
          <td>{{form.numeroDtL}}</td>
        </tr>


    </table>
        <button class="btn btn-primary" type="submit">{{btn_name}}</button>
    </form>

</div>

golchivoapp/templates/alineaciones/alineacion_detail.html
<h1>{{template_title}}</h1>

{{instance.nombre_jugador_local}} </br>
{{instance.numero_jugador_local}}</br>
{{instance.nombre_jugador_visita}}</br>
{{instance.numero_jugador_visita}}</br>

golchivoapp/templates/alineaciones/alineacion_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1>{{template_title}}</h1>

<div class="col-md-6 ">
    <div class="panel panel-default text-center">
        <div class="panel-body">
            <table class="table text-left">
                <tr>
                  <td> Nombre jugador local</td>
                  <td>No.</td>
                  <td>Nombre jugador visita</td>
                  <td>No.</td>
                </tr>
            {% for item in object_list %}
                <tr>
                    <td>{{item.nombreJL1}}</td>
                    <td>{{item.numeroJL1}}</td>
                    <td>{{item.nombreJV1}}</td>
                    <td>{{item.numeroJV1}}</td>
                </tr>
                <tr>
                    <td>{{item.nombreJL2}}</td>
                    <td>{{item.numeroJL2}}</td>
                    <td>{{item.nombreJV2}}</td>
                    <td>{{item.numeroJV2}}</td>
                </tr>
                <tr>
                    <td>{{item.nombreJL3}}</td>
                    <td>{{item.numeroJL3}}</td>
                    <td>{{item.nombreJV3}}</td>
                    <td>{{item.numeroJV3}}</td>
                </tr>
                <tr>
                    <td>{{item.nombreJL4}}</td>
                    <td>{{item.numeroJL4}}</td>
                    <td>{{item.nombreJV4}}</td>
                    <td>{{item.numeroJV4}}</td>
                </tr>
                <tr>
                    <td>{{item.nombreJL5}}</td>
                    <td>{{item.numeroJL5}}</td>
                    <td>{{item.nombreJV5}}</td>
                    <td>{{item.numeroJV5}}</td>
                </tr>
                <tr>
                    <td>{{item.nombreJL6}}</td>
                    <td>{{item.numeroJL6}}</td>
                    <td>{{item.nombreJV6}}</td>
                    <td>{{item.numeroJV6}}</td>
                </tr>
                <tr>
                    <td>{{item.nombreJL7}}</td>
                    <td>{{item.numeroJL7}}</td>
                    <td>{{item.nombreJV7}}</td>
                    <td>{{item.numeroJV7}}</td>
                </tr>
                <tr>
                    <td>{{item.nombreJL8}}</td>
                    <td>{{item.numeroJL8}}</td>
                    <td>{{item.nombreJV8}}</td>
                    <td>{{item.numeroJV8}}</td>
                </tr>
                <tr>
                    <td>{{item.nombreJL9}}</td>
                    <td>{{item.numeroJL9}}</td>
                    <td>{{item.nombreJV9}}</td>
                    <td>{{item.numeroJV9}}</td>
                </tr>
                <tr>
                    <td>{{item.nombreJL10}}</td>
                    <td>{{item.numeroJL10}}</td>
                    <td>{{item.nombreJV10}}</td>
                    <td>{{item.numeroJV10}}</td>
                </tr>
                <tr>
                    <td>{{item.nombreJL11}}</td>
                    <td>{{item.numeroJL11}}</td>
                    <td>{{item.nombreJV11}}</td>
                    <td>{{item.numeroJV11}}</td>
                </tr>
                <tr>
                    <td>{{item.nombreDtL}}</td>
                    <td>{{item.numeroDtL}}</td>
                    <td>{{item.nombreDtV}}</td>
                    <td>{{item.numeroDtV}}</td>
                </tr>

            {% endfor%}
            </table>
        <a class="btn btn-primary btn-sm" href="{% url 'jornada_actual:alin_create' %}">Crear</a>
        {% for item in object_list %}
            <a class="btn btn-primary btn-sm" href="{% url 'jornada_actual:alin_update' item.id %}">Editar</a>
              <a class="btn btn-primary btn-sm" href="{% url 'jornada_actual:alin_delete' item.id %}">eliminar</a>
        {% endfor%}

        </div>
    </div>
</div>

    <div class="col-md-2">
        <div class="panel panel-default">
             <div class="panel-body">
                 <a class="btn btn-primary" href="{% url 'jornada_actual:list' %}">jornada</a> </br> </br>
                 <a class="btn btn-primary" href="http://127.0.0.1:8000/jornada_actual/directoApi/">Directo</a></br></br>
                 <a class="btn btn-primary" href="{% url 'jornada_actual:cronica_list' %}">Cronica</a></br></br>
                 <a class="btn btn-primary" href="{% url 'jornada_actual:result_list' %}">Resultados</a></br></br>
             </div>
        </div>
    </div>
{% endblock %}